name: Build Custom OS

on:
  workflow_dispatch:
    inputs:
      board:
        description: '选择目标开发板 (Target Board)'
        required: true
        default: 'orangepi-5b'
        type: choice
        options:
          - orangepi-5b
          - orangepi-5
          - orangepi-5-plus
          - rock-5b
          - rock-5a
          - nanopc-t6
          - nanopi-r6s
          - radxa-zero3
          - armsom-sige7
          - turing-rk1
      flavor:
        description: '选择系统形态 (Flavor)'
        required: true
        default: 'server'
        type: choice
        options:
          - server
          - desktop
      suite:
        description: '选择 Ubuntu 版本 (Suite)'
        required: true
        default: 'noble'
        type: choice
        options:
          - noble
          - jammy

run-name: Build ${{ github.event.inputs.suite }}-${{ github.event.inputs.flavor }} for ${{ github.event.inputs.board }}

jobs:
  rootfs:
    # 【核心修复 1】：将 ubuntu-latest 锁定为 ubuntu-22.04，解决 python2 等包找不到的问题
    runs-on: self-hosted
    name: Build rootfs 
    steps:
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout LFS
        shell: bash
        run: git lfs fetch && git lfs checkout

      - name: Install dependencies
        shell: bash
        # 【核心修复 2】：为所有的 apt-get 命令补齐 sudo 提权，解决 lock-frontend 报错
        run: |
          sudo apt-get update -o DPkg::Lock::Timeout=60 && sudo apt-get purge needrestart -y && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools

      - name: Build
        shell: bash
        run: sudo ./build.sh --suite=${{ github.event.inputs.suite }} --flavor=${{ github.event.inputs.flavor }} --rootfs-only

      - name: Upload
        uses: actions/upload-artifact@v4.3.3
        with:
            name: ubuntu-${{ github.event.inputs.suite == 'jammy' && '22.04' || github.event.inputs.suite == 'noble' && '24.04' }}-preinstalled-${{ github.event.inputs.flavor }}-arm64-rootfs
            path: ./build/ubuntu-${{ github.event.inputs.suite == 'jammy' && '22.04' || github.event.inputs.suite == 'noble' && '24.04' }}-preinstalled-${{ github.event.inputs.flavor }}-arm64.rootfs.tar.xz
            if-no-files-found: error

  kernel:
    # 【核心修复 1】
    runs-on: self-hosted
    name: Build kernel 
    steps:
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout LFS
        shell: bash
        run: git lfs fetch && git lfs checkout

      - name: Install dependencies
        shell: bash
        # 【核心修复 2】
        run: |
          sudo apt-get update -o DPkg::Lock::Timeout=60 && sudo apt-get purge needrestart -y && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools

      - name: Build
        shell: bash
        run: sudo ./build.sh --suite=${{ github.event.inputs.suite }} --kernel-only

      - name: Upload
        uses: actions/upload-artifact@v4.3.3
        with:
            name: linux-rockchip-${{ github.event.inputs.suite == 'jammy' && '5.10' || github.event.inputs.suite == 'noble' && '6.1' }}
            path: ./build/linux-*.deb
            if-no-files-found: error

  build:
    # 【核心修复 1】
    runs-on: self-hostedubuntu-22.04
    needs: [rootfs, kernel]
    name: Build image 
    steps:
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout LFS
        shell: bash
        run: git lfs fetch && git lfs checkout

      - name: Install dependencies
        shell: bash
        # 【核心修复 2】
        run: |
          sudo apt-get update -o DPkg::Lock::Timeout=60 && sudo apt-get purge needrestart -y && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools

      - name: Checkout rootfs
        uses: actions/download-artifact@v4.1.2
        with:
            name: ubuntu-${{ github.event.inputs.suite == 'jammy' && '22.04' || github.event.inputs.suite == 'noble' && '24.04' }}-preinstalled-${{ github.event.inputs.flavor }}-arm64-rootfs
            path: ./build/

      - name: Checkout kernel
        uses: actions/download-artifact@v4.1.2
        with:
            name: linux-rockchip-${{ github.event.inputs.suite == 'jammy' && '5.10' || github.event.inputs.suite == 'noble' && '6.1' }}
            path: ./build/

      - name: Build
        shell: bash
        run: sudo ./build.sh --board=${{ github.event.inputs.board }} --suite=${{ github.event.inputs.suite }} --flavor=${{ github.event.inputs.flavor }}

      - name: Upload
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ubuntu-${{ github.event.inputs.suite == 'jammy' && '22.04' || github.event.inputs.suite == 'noble' && '24.04' }}-preinstalled-${{ github.event.inputs.flavor }}-arm64-${{ github.event.inputs.board }}
          path: ./images/ubuntu-*-preinstalled-${{ github.event.inputs.flavor }}-arm64-${{ github.event.inputs.board }}.*
          if-no-files-found: error

      - name: Clean cache
        shell: bash
        run: sync && sudo rm -rf ./images/ ./build/ && sync
